# Generated by Django 3.0.6 on 2020-05-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20200510_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Man items', 'Man items'), ('Ladies items', 'Ladies items'), ('Electric items', 'Electric items'), ('Grocery items', 'Grocery items'), ('Medical items', 'Medical items'), ('Laptop items', 'Laptop items')], max_length=200, null=True),
        ),
    ]
