# Generated by Django 3.0.6 on 2020-05-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20200511_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Men shoes and clothing', 'Men shoes and clothing'), ('Women shoes and clothing', 'Women shoes and clothing'), ('Electronic Devices', 'Electronic Devices'), ('Electronic accessories', 'Electronic accessories'), ('Grocery items', 'Grocery items'), ('Medical items', 'Medical items')], max_length=200, null=True),
        ),
    ]
