# Generated by Django 3.0.6 on 2020-06-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_product_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='device',
        ),
        migrations.AddField(
            model_name='customer',
            name='device',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
